version: '3'
services:
  suricata:
    build:
      context: ./services
      dockerfile: ./suricata/Dockerfile
    cap_add: 
      - NET_ADMIN
      - SYS_NICE
    volumes:
      - /var/log/suricata:/var/log/suricata:rw
      - /var/log/suricata:/home/suricata
      - ./services/suricata/dataset:/home/dataset
      - ./services/suricata/config/docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      - SURICATA_OPTIONS=-i ${INTERFACE} --set vars.address-groups.HOME_NET=${HOME_NET}
      - PGID=${GID:-1000}
      - PUID=${UID:-1000}
      - SURICATA_INTERFACE=${INTERFACE}
      - SURICATA_HOME_NET=${HOME_NET}
      - COMMUNITY_ID=${COMMUNITY_ID}
    network_mode: host
networks:  
  elk:
    driver: bridge

